// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticoDotNet.Data;

#nullable disable

namespace PracticoDotNet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240420154827_NuevosDatosParaPaisesYConfederacion")]
    partial class NuevosDatosParaPaisesYConfederacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PracticoDotNet.Models.Confederacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Fundacion")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Confederacion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Fundacion = new DateOnly(1, 1, 1),
                            Nombre = "AUF"
                        });
                });

            modelBuilder.Entity("PracticoDotNet.Models.Deporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Deporte");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Futbol"
                        });
                });

            modelBuilder.Entity("PracticoDotNet.Models.Pais", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("id");

                    b.ToTable("Paises");

                    b.HasData(
                        new
                        {
                            id = 1,
                            nombre = "Uruguay"
                        },
                        new
                        {
                            id = 2,
                            nombre = "Argentina"
                        },
                        new
                        {
                            id = 3,
                            nombre = "Brasil"
                        },
                        new
                        {
                            id = 4,
                            nombre = "Venezuela"
                        },
                        new
                        {
                            id = 5,
                            nombre = "Paraguay"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
