// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticoDotNet.Data;

#nullable disable

namespace PracticoDotNet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240415022543_AgregarListaDePaises")]
    partial class AgregarListaDePaises
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PracticoDotNet.Models.Pais", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Paises");

                    b.HasData(
                        new
                        {
                            id = 1,
                            nombre = "Uruguay"
                        },
                        new
                        {
                            id = 2,
                            nombre = "Argentina"
                        },
                        new
                        {
                            id = 3,
                            nombre = "Brasil"
                        },
                        new
                        {
                            id = 4,
                            nombre = "Venezuela"
                        },
                        new
                        {
                            id = 5,
                            nombre = "Paraguay"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
